### ISSUE TITLE
Crash when used with Node 8.8.0 in Electron

### ISSUE THREAD

**Issue by bengotow** [isaacs/natives#16]
Hey @isaacs! Thanks for writing `natives` and `graceful-fs`. I recently upgraded a large project (https://github.com/Foundry376/Mailspring) to use Electron 1.8 / Node 8.8.0, and `natives` is causing a hard crash of NodeJS when the app launches.

I've traced the issue down quite a bit over in https://github.com/electron/electron/issues/10905, and it looks like `natives` is re-loading `async_hooks.js`, which causes an assertion failure.

I know `natives` is fragile (love the disclaimer in the README!) but it's used within `graceful-fs`, and it seems `graceful-fs` is used... quite a bit! In one user's case it's within `unzip` and it looks like several Mailspring dependencies use it as well. I'm not sure if there's a way to work around the assertion failure, but I'd love if you could take a look and offer some insight on the best path forward.

**Comment by isaacs** [comment]
The latest version of graceful-fs doesn’t use natives. Versions of graceful-fs from 3.x and before are deprecated for this reason. It will likely never work in new node versions. 

Upgrade graceful-fs, or downgrade node. No other way forward.

**Comment by bengotow** [comment]
Awesome thanks! Somehow I'd missed that it'd been removed in recent versions.
