### ISSUE TITLE
cannot install natives 

### ISSUE THREAD

**Issue by BenjaminEckardt** [isaacs/natives#5]
Hello,

using natives via npm install does not work.

Tested on 
Windows 7
node version 4.5.0
npm version 2.15.9

```
D:\npmlesstest>npm install natives
npm WARN package.json npmlesstest@1.0.0 No description
npm WARN package.json npmlesstest@1.0.0 No repository field.
npm WARN package.json npmlesstest@1.0.0 No README data
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "natives"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! Cannot convert undefined or null to object
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
\
npm ERR! Please include the following file with any support request:
npm ERR!     D:\npmlesstest\npm-debug.log

D:\npmlesstest>
```

The error also occurs when using graceful-fs as an optional dependency like [less](https://www.npmjs.com/package/less) in version 2.4.0 does.

Best regards

**Comment by matthewpucc** [comment]
Bump. We're seeing this issue too.

**Comment by ChALkeR** [comment]
Doesn't look like a `natives` issue, as it shouldn't execute any `natives`-specific code on `npm install natives` — this package has no post/pre-install scripts.

Perhaps report this to https://github.com/npm/npm/issues with attaching the `npm-debug.log`, as suggested?

**Comment by matthewpucc** [comment]
Will do.  Thanks.

**Comment by darbo1353** [comment]
@ChALkeR I don't believe that it is an issue with npm. I can run the following commands and natives ins't found as a module. Can you or someone verify that after the v1.0.2 build, this module is still properly listed with npm? Because according to the `npm view natives` command, y'all have no released versions or exist at all in npm. 

My interest in this issue is because your module is used in graceful-js, which is used in bower, which is heavily used in my projects.

Tested on:
Windows 10
node: 4.5.0
npm: 2.15.9

```
C:\Users\bcoffman\Documents\Stash\Product-Saphron\src\project\Applications\Work Orders - External\src>npm install natives@1.0.1
npm WARN package.json Saphron-WorkOrder@0.1.0 No description
npm WARN package.json Saphron-WorkOrder@0.1.0 No repository field.
npm WARN package.json Saphron-WorkOrder@0.1.0 No README data
npm WARN package.json Saphron-WorkOrder@0.1.0 No license field.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "natives@1.0.1"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! Cannot read property '1.0.1' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bcoffman\Documents\Stash\Product-Saphron\src\project\Applications\Work Orders - External\src\npm-debug.log
```

```
C:\Users\bcoffman\Documents\Stash\Product-Saphron\src\project\Applications\Work Orders - External\src>npm view natives

C:\Users\bcoffman\Documents\Stash\Product-Saphron\src\project\Applications\Work Orders - External\src>''
```

Thanks!

**Comment by isaacs** [comment]
@darbo1353 That's pretty weird.

Here's what I see on my machine:

```
$ npm view natives versions
[ '1.0.0', '1.0.1', '1.0.2' ]
```

So, 1.0.0, 1.0.1, and 1.0.2 should be valid versions.  If you go to http://registry.npmjs.org/natives you can see all the versions there.  You can download from https://registry.npmjs.org/natives/-/natives-1.0.1.tgz directly to see that it actually exists.

Can you try updating to the latest version of npm, clearing your cache with `npm cache clear` or perhaps make sure that your app isn't requiring some other version somewhere else?  Maybe `npm config ls` might be informative here?

**Comment by ChALkeR** [comment]
@darbo1353 
> `C:\Users\bcoffman\Documents\Stash\Product-Saphron\src\project\Applications\Work Orders - External\src`

Just to be sure — is this reproducable from a shorter path? Does removing spaces help?

**Comment by darbo1353** [comment]
@isaacs and @ChALkeR This is so weird. I followed your advice and updated to the most recent npm. So my system is:
Windows 10
Node: 4.5.0
npm: 3.10.6

```
C:\Users\bcoffman\Documents\Temp>npm view natives
undefined
```
Before getting the undefined I was getting nothing so at least that changed, but I still can't find your node module at all.

I've tried clearing my cache with `npm cache clear` and tried to review anything suspicious in `npm config ls`.

I still fail trying to install:
```
C:\Users\bcoffman\Documents\Temp>npm install natives@1.0.1
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\bcoffman\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "natives@1.0.1"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6

npm ERR! Cannot convert undefined or null to object
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bcoffman\Documents\Temp\npm-debug.log
```

I have found that y'all are being talked about in this issue over here in npmjs:  https://github.com/npm/npm/issues/12502 (Scroll to the bottom)

Do either of you know of anything else I could be doing wrong? Or any long shots that could be the issue?

Thanks for looking at this!

**Comment by isaacs** [comment]
@darbo1353 That file at `C:\Users\bcoffman\Documents\Temp\npm-debug.log`, upload it to https://gist.github.com and post a link here.

**Comment by darbo1353** [comment]
@isaacs Here you go. https://gist.github.com/darbo1353/6c5e5ad4fdb1f7ca76a2035c751b1bfc

**Comment by BenjaminEckardt** [comment]
@darbo1353 Do you use any kind of local npm registry?

**Comment by darbo1353** [comment]
@BenjaminEckardt Yes. We use a local registry for our private modules.

**Comment by isaacs** [comment]
@darbo: You have to add the natives package to nexus, it looks like. Also, it appears that nexus is returning an invalid reaponse that the npm cli doesn't know how to handle, so that might be a bug to tell the sonatype folks about.

**Comment by BenjaminEckardt** [comment]
Seems to have been the same cause here. Sorry for opening.
