### ISSUE TITLE
Hide internal modules.

### ISSUE THREAD

**Issue by Fishrock123** [isaacs/natives#8]
To prevent people depending on `internal/` modules, this module should hide them form direct use.

If not, it should be clearly marked as "DO NOT USE", should link to https://github.com/nodejs/node/blob/master/lib/internal/readme.md, and state that dependants can and will break at any time when access internals with no support for those APIs from the Node Core team.

(If people need access to something normally only covered by those APIs, we should expose a proper API we can maintain for it.)

**Comment by vkurchatkin** [comment]
> To prevent people depending on internal/ modules, this module should hide them form direct use

I'm not sure there is a point. Whether people use `internal/` or not, it's still unsupported.

**Comment by isaacs** [comment]
Literally everything about this module is unsupported, and the majority of the readme is devoted to explaining this as explicitly as possible. 

I would be happy to include a link in the readme to a statement from the CTC or you personally saying that this is a bad idea. I say it's a bad idea in the docs.

I believe that is sufficient warning. it's unlikely anyone will be able to find or use this module without seeing the readme at least once.
